# filepath: params.yaml
drive:
  ros__parameters:
    linear_x_coeff: 1.0
    linear_x_offset: 0.0
    linear_x_min: -0.4
    linear_x_max: 0.4

    linear_y_coeff: 1.0
    linear_y_offset: 0.0
    linear_y_min: -1000.0
    linear_y_max: 1000.0

    linear_z_coeff: 1.0
    linear_z_offset: 0.0
    linear_z_min: -1000.0
    linear_z_max: 1000.0

    angular_x_coeff: 1.0
    angular_x_offset: 0.0
    angular_x_min: -1000.0
    angular_x_max: 1000.0

    angular_y_coeff: 1.0
    angular_y_offset: 0.0
    angular_y_min: -1000.0
    angular_y_max: 1000.0

    angular_z_coeff: 1.0
    angular_z_offset: 0.0
    angular_z_min: -0.26
    angular_z_max: 0.65

    controller_type: "ackermann"
    output_frame_id: "drive"

aeb:
  ros__parameters:
    ttc_threshold: 5.0
    aeb_aktiv: 1
    controller_type: "ackermann"