controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"

      # Disable costmap usage
      use_costmap: false
      costmap_topic: ""

      # Controller parameters
      desired_linear_vel: 1.5
      min_linear_vel: 0.5
      max_linear_vel: 2.0
      max_lookahead_dist: 0.5
      min_lookahead_dist: 0.2
      lookahead_time: 0.5
      use_velocity_scaled_lookahead_dist: true
      curvature_lookahead_dist: 0.5
      transform_tolerance: 0.2

local_costmap/local_costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 10.0
    publish_frequency: 5.0
    width: 60        # 3.0m / 0.05m = 60 cells
    height: 60       # 3.0m / 0.05m = 60 cells
    resolution: 0.05
    rolling_window: true
    plugins: ["obstacle_layer", "inflation_layer"]

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      observation_sources: "camera_grid"
      camera_grid:
        topic: /lane_grid
        max_obstacle_height: 2.0
        clearing: true
        marking: true

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: true