costmap/costmap:
  ros__parameters:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 10.0
    publish_frequency: 5.0
    width: 3.0
    height: 3.0
    resolution: 0.05
    rolling_window: true
    plugins: ["obstacle_layer", "inflation_layer"]

    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enabled: true
      observation_sources: "camera_grid"
      camera_grid:
        topic: /occ_grid
        max_obstacle_height: 2.0
        clearing: true
        marking: true

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      enabled: true