controller_server:
  ros__parameters:
    use_sim_time: true
    controller_plugins: ["FollowPath"]

    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"

      # Disable costmap usage
      use_costmap: false
      costmap_topic: ""

      # Controller parameters
      desired_linear_vel: 0.5
      min_linear_vel: 0.1
      max_linear_vel: 1.0
      max_lookahead_dist: 1.0
      min_lookahead_dist: 0.3
      lookahead_time: 1.5
      use_velocity_scaled_lookahead_dist: false
      curvature_lookahead_dist: 1.0
      transform_tolerance: 0.2